### ISSUE TITLE
update needed for Inkscape version 1.0

### ISSUE THREAD

**Issue by brynnd** [drphonon/Inkscape_LivingHinge#5]
Hello,
Thank you for providing this extension for Inkscape users!

This is just to let you know that most 3rd party Inkscape extensions, like this one, probably will not work with the upcoming new Inkscape version, the long-awaited version 1.0.

Here is the info you need to update this extension, so that it will work with 1.0 and future versions.  
https://wiki.inkscape.org/wiki/index.php?title=Updating_your_Extension_for_1.0

If you have further questions, you can contact Inkscape developers via [mailing lists](https://lists.inkscape.org/postorius/lists/?all-lists), [forum](https://inkscape.org/forums/extensions/), or the [chatroom](https://chat.inkscape.org/channel/inkscape_extensions).

If you have already updated it, please disregard this message.

All best,
brynn

**Comment by Pilarina63** [comment]
I hope it works. I need it!

**Comment by Anool** [comment]
Updated to Inkscape ver 1.0, and as anticipated above, living_hinge extension does not work.

Inkscape ver 1.0 (1.0+r73) on Ubuntu 18.04.4 LTS

ERROR as below ::

living_hinge.py:49: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--unit',action='store',type='string', dest='unit',default='mm',help='units of measurement')
living_hinge.py:50: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--cut_length',action='store',type='float', dest='cut_length',default=0,help='length of the cuts for the hinge.')
living_hinge.py:51: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--gap_length',action='store',type='float', dest='gap_length',default=0,help='separation distance between successive hinge cuts.')
living_hinge.py:52: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`.You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option('--sep_distance',action='store',type='float', dest='sep_distance',default=0,help='distance between successive lines of hinge cuts.')
living_hinge.py:180: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  effect.affect()
living_hinge.py:58: DeprecationWarning: Effect.unittouu is now a method in the svg document. Use `self.svg.unittouu(str)` instead.
  l = self.unittouu(str(self.options.cut_length) + unit)
living_hinge.py:60: DeprecationWarning: Effect.unittouu is now a method in the svg document. Use `self.svg.unittouu(str)` instead.
  d = self.unittouu(str(self.options.gap_length) + unit)
living_hinge.py:63: DeprecationWarning: Effect.unittouu is now a method in the svg document. Use `self.svg.unittouu(str)` instead.
  dd = self.unittouu(str(self.options.sep_distance) + unit)
living_hinge.py:66: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  if self.selected:
living_hinge.py:68: DeprecationWarning: Effect.current_layer is now a method in the svg. Use `self.svg.get_current_layer()` instead.
  parent = self.current_layer
living_hinge.py:69: DeprecationWarning: Effect.selected is now a dict in the svg. Use `self.svg.selected`.
  for id, node in self.selected.iteritems():
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp
Traceback (most recent call last):
  File "living_hinge.py", line 180, in <module>
    effect.affect()
  File "/usr/share/inkscape/extensions/inkex/deprecated.py", line 180, in affect
    return self.run(args=args)
  File "/usr/share/inkscape/extensions/inkex/base.py", line 123, in run
    self.save_raw(self.effect())
  File "living_hinge.py", line 69, in effect
    for id, node in self.selected.iteritems():
AttributeError: 'collections.OrderedDict' object has no attribute 'iteritems'

**Comment by sebwouaib** [comment]
Here a modified version for Inkscape 1.0 :
[1.0.zip](https://github.com/drphonon/Inkscape_LivingHinge/files/4925554/1.0.zip)
Feel free to intergrate it

**Comment by aramperez** [comment]
Thanks @sebwouaib, I was searching for an updated version!

**Comment by ChrisAndersen2700** [comment]
Sadfully doesn´t work with 1.1 :-( :-( :-(

**Comment by sebwouaib** [comment]
> Sadfully doesn´t work with 1.1 :-( :-( :-(

Hum strange, It works for me in 1.1. Do you have an error message ?
Be sure to copy files in "C:\Program Files\Inkscape\share\inkscape\extensions" (on windows)

**Comment by drphonon** [comment]
Did sebwouaib's suggestion work?

**Comment by ChrisAndersen2700** [comment]
There´s no \share folder, but does show up in the program it self. : C:\Users\chris\AppData\Roaming\inkscape\extensions and the the inx and py
Inkscape 1.1.1 (3bf5ae0d25, 2021-09-20)
I get: "C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:360: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:363: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:366: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:370: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:373: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:377: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:380: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:383: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:387: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:390: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:393: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:397: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:400: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:404: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:407: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:410: DeprecationWarning: Effect.OptionParser or `optparse` has been deprecated and replaced with `argparser`. You must change `self.OptionParser.add_option` to `self.arg_parser.add_argument`; the arguments are similar.
  self.OptionParser.add_option(
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:496: DeprecationWarning: Effect.affect is now `Effect.run()`. The `output` argument has changed.
  LivingHingeEffect().affect()
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:424: DeprecationWarning: Effect.unittouu is now a method in the SvgDocumentElement class. Use `self.svg.unittouu(str)` instead.
  stroke_width = self.unittouu("0.2mm")
C:\Users\chris\AppData\Roaming\inkscape\extensions\living_hinge.py:415: DeprecationWarning: Effect.unittouu is now a method in the SvgDocumentElement class. Use `self.svg.unittouu(str)` instead.
  return self.unittouu(str(value) + self.options.unit)
Select a valid pattern tab before rendering.
"
